export const coupleQuestions = [
  "Who was your first crush, and what were they like?",
  "Can you describe your first heartbreak?",
  "What was the biggest lesson from your worst breakup?",
  "What's something you used to believe about relationships but no longer do?",
  "What's something surprising that you were afraid of as a child?",
  "What was your childhood bedroom like?",
  "What was your favorite food growing up?",
  "What's your favorite meal now?",
  "What nicknames did you have as a kid?",
  "What was the first album you ever owned?",
  "How does your life compare to how you imagined it growing up?",
  "What was your dream job when you were a kid?",
  "Were you \"popular\" in high school?",
  "What was your favorite school subject growing up?",
  "Was there an embarrassing fashion moment in your adolescence?",
  "What's your definition of romance?",
  "Do you see yourself having kids? If so, how many?",
  "Do you believe in soulmates?",
  "If you believe in soulmates, do you think you've met yours?",
  "Do you believe in God?",
  "Is going to church or another house of worship important to you?",
  "Do you think it's more important to be smart or to be kind?",
  "Would you rather be loved, respected, or admired?",
  "What does a successful life look like to you?",
  "Does your family have any traditions?",
  "Would you want to create any traditions in your family going forward?",
  "What do you think is your best quality?",
  "What qualities or character traits do you want to work on?",
  "What's one of my best qualities?",
  "What do you find sexiest about me?",
  "Have you ever been cheated on?",
  "Have you ever cheated on someone?",
  "How old were you when you lost your virginity?",
  "What was your first sexual experience like?",
  "Do you think infidelity is always a deal breaker, no matter what?",
  "Who is more trusting, you or me?",
  "Who is more inclined to be jealous, you or me?",
  "What's the first thing you noticed about me?",
  "What's the first thing you found attractive about me?",
  "Is there a personality trait that always ticks you off?",
  "How do you hide anger when you don't want it to show?",
  "How do you talk yourself down from anger or frustration?",
  "Who is more of a risk-taker, you or me?",
  "A movie is made about your life. Which actor would you cast as yourself?",
  "Do you have a bucket list?",
  "What's on your bucket list?",
  "What's your dream vacation?",
  "Where do you want to travel to next and why?",
  "Where would be your ideal place—or places—to live?",
  "Would you rather own a home you don't love or rent one you love?",
  "What's something you'd like to try doing but haven't worked up the nerve to yet?",
  "Would you rather be an amazing singer or an incredible dancer?",
  "What superpower do you wish you could have?",
  "What activity makes you feel the most joyful when you're doing it?",
  "What would you do with your life if you suddenly became a billionaire?",
  "Do you think there's such a thing as luck, or do we create our own outcomes?",
  "Who is more generous, you or me?",
  "Do you remember your dreams when you wake up?",
  "If so, do you ever dream about me?",
  "What's your favorite thing about our relationship?",
  "What's something you'd like for us to try?",
  "What's something not obviously sexual that turns you on?",
  "What's an instant turn-on for you?",
  "Do you have a sexual fantasy you've never shared with me before?",
  "If we could have sex anywhere, where would you choose?",
  "Would you rather have only morning sex for the rest of your life or strictly sex at night?",
  "What was your very first orgasm like?",
  "Have you ever faked an orgasm—not necessarily with me, but in general?",
  "How do you define great sex?",
  "Have you ever thought about me while masturbating?",
  "Does the idea of getting caught during sex excite you?",
  "Does the thought of someone watching us have sex excite you?",
  "When did you first want to kiss me?",
  "Is there a type of outfit or clothes you find sexy that you'd like to see me in?",
  "Do you like playing with sex toys, or would you like to try them as a couple?",
  "What's your favorite sex position?",
  "What's something you wish we did together more often?",
  "Where would you like to be touched more often?",
  "Who is more likely to survive the Hunger Games—me or you?",
  "You're stuck on a deserted island. What three foods would you want an endless supply of?",
  "Who is more likely to live through a zombie attack?",
  "How old were you when you stopped believing in the tooth fairy?",
  "How old were you when you stopped believing in Santa?",
  "Would you rather be a vampire or a werewolf?",
  "What's your go-to karaoke song and why?",
  "What historical era would you most, and least, want to live in?",
  "Who is your favorite couple in pop culture?",
  "Who was your first celebrity crush?",
  "Who's your \"hall pass\" celebrity crush today?",
  "If you could have dinner with anyone, alive or dead, who would it be?",
  "Which of us has a better sense of direction?",
  "What's a skill you've always wanted to learn, and what has stopped you from doing it?",
  "Do you think of yourself as an optimist or a pessimist?",
  "Do you believe that everything happens for a reason?",
  "Which musical artist would you want me to commission a love song from?",
  "Which song describes our love story best?",
  "Is there a song that makes you think of me?",
  "What animal would you choose to be in another life?",
  "What animal do you think I'd be?",
  "Do you believe in ghosts?",
  "If you were a ghost, who would you haunt?",
  "Do you believe in reincarnation?",
  "What do you think happens after we die?",
  "Do you think people can really have psychic abilities?",
  "If you had the option to live forever, would you choose to?",
  "What's your favorite movie of all time?",
  "What's a song you could sing by heart to me, right now?",
  "Do you like to be surprised?",
  "Do you believe in astrological compatibility?",
  "How many times have you been in love?",
  "Have you ever been in a physical fight?",
  "Is there a personal goal you'd like to achieve in the next five years or so?",
  "Do you consider yourself good with money?",
  "If you could describe our relationship in one word, what would it be?",
  "Do you think there's such a thing as a \"harmless\" lie?",
  "What's the best trip you've ever taken?",
  "What's the worst trip you've ever taken?",
  "If you started a YouTube channel or blog, what would it focus on?",
  "Would you rather live in only hot weather forever or only cold weather?",
  "Do you have a personal flaw you'd fix, if you could?",
  "Is there anything you've always wondered about me but have hesitated to ask?",
  "What's the best gift you've ever been given?",
];
